### ISSUE TITLE
Allow referencing configuration variables

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#1]
Currently the Dynatrace Monitoring as Code tool only allows to reference the id/name of created Dynatrace objects

Referencing variables from another yaml configuration is not possible, but would be helpful.
E.g. to reference the names of metrics from a plugin configuration in a dashboard configuration

**Comment by didiladi** [comment]
Relates to discussions:

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/208
https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/165
