### ISSUE TITLE
Add application detection rules ordering

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#10]
For application detection rules, there is an API which enables a user to define the ordering of application detection rules.

Add support for this API in Dynatrace Monitoring as Code.

**Comment by didiladi** [comment]
That's the API: https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/rum/application-detection-configuration/reorder-rules/

**Comment by tatomir146** [comment]
Ordering functionality will be, according to swagger docs, available with all settings 2.0 configuration. There is `insertAfter` parameter.

**Comment by UnseenWizzard** [comment]
Rule ordering can be achieved as a workaround by using references between configurations: https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/Guides/ordering_app_detection_rules

Settings 2.0 API supports ordering via `insertAfter` (but might not be in scope of initial Settings support)

As such closing the old feature idea for handling this on the config api
