### ISSUE TITLE
Trim URL Trailing Slashes

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#102]
**Is your feature request related to a problem? Please describe.**
Environment URLs containing trailing slashes cause the tool to fail as it'll reach out to `https://abc123.live.dynatrace.com//api`

**Describe the solution you'd like**
Trim any trailing slashes

**Comment by Dynatrace-Adam-Gardner** [comment]
#103

**Comment by patrickpichler** [comment]
Fixed by #166
