### ISSUE TITLE
Handle breaking change in Dashboard API in version 1.208+

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#105]
**Description**
There is a breaking change in version `1.208+` coming for the Dashboard API:

```
1) POST - /dashboards - Create a new dashboard

BEFORE:
• the owner property in the dashboardMetadata object within the request body must be null or undefined, otherwise the validation fails
• the sharingDetails property is present in dashboardMetadata

1.208+:
• It becomes mandatory to specify the owner property as a non-null value, otherwise the validation fails.
• dropped sharingDetails from dashboardMetadata
```

```
2) PUT - /dashboards/{id} - Update a dashboard

BEFORE:
• the owner property is not properly validated to always be not-null
• the sharingDetails property is present in dashboardMetadata

1.208+:
• the owner property will be always validated to be not-null
• dropped sharingDetails from dashboardMetadata
```

```
3) GET - /dashboards/{id} - Get a dashboard
BEFORE:
• the sharingDetails property is present in dashboardMetadata

1.208+:
• dropped sharingDetails from dashboardMetadata
```

Since this API is still in early-adoper state, its version will not be increased.

This is especially painful if the same configuration needs to be applied to environments in different versions. `monaco` should handle the apply of the config for the user in a graceful fashion. 

**Describe the solution you'd like**
If you try to apply a dasboard configuration with the old (pre `1.208`) format to an enviromnent which is on `1.208+`:
* `monaco` should insert a `owners` property into the json before throwing it to the API.
* the user should get a warning message, indicating that the configuration needs to be updated.

If you try to apply a dasboard configuration with the new (`1.208+`) format to an enviromnent which is still on an older version `pre 1.208`:
* `monaco` should remove the `owners` property from the json before throwing it to the API.

**Describe alternatives you've considered**
If you don't need to deploy configuration to multiple environments in different versions, you can fix your configurations like so:

Configuration yaml (note the double quotes `'` and `"` for the owner):

```
myDashboard:
  - name: "My Dashboard"
  - owner: '"my.email@example.com"'
```

Dashboard JSON (there are no quotes for `owners`):

```
{
  "dashboardMetadata": {
    "name": "{{ .name }}",
    "shared": true,
    "owner": {{ .owner }},
   ...
```

**Comment by tatomir146** [comment]
@didiladi this would be the first time `monaco` modifies params on upload depending on cluster version?

**Comment by didiladi** [comment]
@tatomir146 yes, this would be the first time we need to query the dynatrace version first. Do you see any other alternative way of implementing this? :thinking:

**Comment by tatomir146** [comment]
Getting cluster version before updating would totally make sense e.g. to check if API is supported etc but I don't like the idea we are modifying JSON on places where there is no placeholder defined. This can actually be fixed bu just changing configuration and from 208 on this will be the standard. As there is a workaround for this I would probably skip this for now.

**Comment by JACONDE** [comment]
Almost got a heart attach when try to run one of my Azure pipelines and all dashboard set-up was failing, after 3 weeks and it fails when was working before. Until I read this thread.

**Comment by didiladi** [comment]
My intention with this GitHub issue partly was to document the issue and describe the workaround above. I'm happy that this worked. :smile: 

@tatomir146 I agree, this issue can be fixed by changing the configuration when deploying to 1.208+. Its not worth the effort to fix it in `monaco`.

**Comment by didiladi** [comment]
Will be handled/discussed in #209 -> Closing this issue.
