### ISSUE TITLE
Support frequentIssueDetection API

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-monitoring-as-code#115]
**Is your feature request related to a problem? Please describe.**
Support the call to /api/config/v1/frequentIssueDetection

**Describe the solution you'd like**
Make another subfolder like the others api calls to define the payload. e.g.
```
{
        "frequentIssueDetectionApplicationEnabled": true,
        "frequentIssueDetectionServiceEnabled": true,
        "frequentIssueDetectionInfrastructureEnabled": true
}
```

**Describe alternatives you've considered**
None

**Additional context**
Add any other context about the feature request here.

**Comment by didiladi** [comment]
Oh, no... This API needs some more work in monaco, as it doesn't follow our API conventions:
* It just implements `GET` and `PUT`
* There is no `name` attrubute

https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/frequent-issue-detection-api/get-configuration/

**Comment by UnseenWizzard** [comment]
Hi @robertjahn, this is now supported from 1.8.0 upwards as `frequent-issue-detection `
