### ISSUE TITLE
Support service anomalyDetection

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-monitoring-as-code#116]
**Is your feature request related to a problem? Please describe.**
Support the call to /api/config/v1/anomalyDetection/services

**Describe the solution you'd like**
Make another subfolder like the others api calls to define the payload. e.g.
```
{
  "responseTimeDegradation": {
    "detectionMode": "DETECT_AUTOMATICALLY",
    "automaticDetection": {
      "responseTimeDegradationMilliseconds": 100,
      "responseTimeDegradationPercent": 50,
      "slowestResponseTimeDegradationMilliseconds": 1000,
      "slowestResponseTimeDegradationPercent": 100,
      "loadThreshold": "FIVE_REQUESTS_PER_MINUTE"
    }
  },
  "loadDrop": {
    "enabled": false
  },
  "loadSpike": {
    "enabled": false
  },
  "failureRateIncrease": {
    "detectionMode": "DETECT_AUTOMATICALLY",
    "automaticDetection": {
      "failingServiceCallPercentageIncreaseAbsolute": 0,
      "failingServiceCallPercentageIncreaseRelative": 50
    }
  }
}
```

**Describe alternatives you've considered**
None

**Additional context**
Add any other context about the feature request here.

**Comment by UnseenWizzard** [comment]
Hi @robertjahn, Service Anomaly detection is now supported as `anomaly-detection-services` from 1.8.0 upwards :)
