### ISSUE TITLE
Update readme to indicate support for kubernetes credentials

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-monitoring-as-code#120]
**Is your feature request related to a problem? Please describe.**
I saw that issue #3 was closed and I tested and it works, but the readme files table does not indicate this.  

**Describe the solution you'd like**
Update README section - https://github.com/dynatrace-oss/dynatrace-monitoring-as-code#supported-configuration-types-and-token-permissions

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kristofre** [comment]
azure credentials is also missing from the documentation. 
@UnseenWizzard can you please assign me to this one?

**Comment by 163a** [comment]
I added azure, kubernetes credentials to table while I was changing table for #187

with PR:
#236

If happy, this issue may be closed too.

**Comment by didiladi** [comment]
Thanks for tackling this @163a. :rocket:
