### ISSUE TITLE
Improve how information about extension upload is presented to users

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#125]
**Current problem:**
When the extension version is the same as existing version, Monaco deployment will fail (API error) - because Dynatrace rejects uploading extension with same version - even if the extension code remains unchanged.

**Workaround:**
Save the extension YAML with the flag
`- skipDeployment: "true"`

**Possible solutions required:**
Approach A)
Monaco compares extension code, if the extension code changed, auto-increment the extension version and apply it.
Benefits: _fully automated approach_
Approach B)
Monaco compares the extension version, if the version ~matches~ is less than or equal to, skip deployment automatically.
Optionally, allow an additional flag in YAML, like `autoSkipExistingVersion: "true"` to be set on extension.
Benefits: _controlled approach_

**Comment by UnseenWizzard** [comment]
Hi @163a , only just saw this. 
Are you sure that your configuration deployment fails? 
monaco currently should be ignoring these kinds of extension deployment errors. 
I can see that it logs an error, but it should not fail the rest of the deployment on these: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/pkg/rest/extension_upload.go

That is admittedly a lot less elegant than your suggested approaches, but generally your Approach B)

That error handling & logging can certainly be improved, but this should not currently block your deployments

**Comment by 163a** [comment]
Hmm, I will check again if that's the case.

**Comment by 163a** [comment]
You are correct, @UnseenWizzard the project does not fail. Only the extensions with conflicting versions will return an error.

**Comment by UnseenWizzard** [comment]
Hi @163a good to hear. 

For now I would keep this as improve how the current "Approach B)" is presented, hoping that is a quick fix. 
Logging it as an error directly is only useful if you already know that it's monaco's way of handling this.

The fully automated approach of auto-incrementing is a really cool idea, but would be very specific to extensions and not something monaco is currently remotely capable of. The only state it knows are the input config files it's given
