### ISSUE TITLE
Failing gracefully on upload error

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#127]
**Is your feature request related to a problem? Please describe.**
Currently if for some reason (e.g. breaking API change, config in someone else's responsibility...) deployment of a single config (except Plugins) fails, the whole job is stopped. This makes it impossible to deploy new configs before solving a problem.

**Describe the solution you'd like**
If config upload files (response other than 2xx) deployment should proceed and try to upload other configurations. If there are dependencies to the configuration failing to upload, they will also fail gracefully. 

**Additional context**
IMO this shouldn't be a standard upload case, but we could add support with a flag (--force, --follow-on-error or something similar)

**Comment by tatomir146** [comment]
@patrickpichler @UnseenWizzard @didiladi let me hear your opinion on this one? :) Thanks!

**Comment by didiladi** [comment]
I agree, we definitely need that for our internal use cases. :+1: How about `--continue-on-error`?

**Comment by patrickpichler** [comment]
`--continue-on-error` sounds good :+1:

**Comment by UnseenWizzard** [comment]
The one issue I see with that (and why we continue with the next env, but not the next config right now) are dependencies. 

If I have configs A<-B<-C and A fails, B and C will fail as well.

If we're fine with deploying half-way broken configs that's ok

**Comment by tatomir146** [comment]
@UnseenWizzard so the job should still return error, and of course all configs having dependency on failing config will also fail. As said, this shouldn't be a default run mode of monaco.
