### ISSUE TITLE
monaco init command for project initialisation 

### ISSUE THREAD

**Issue by kristofre** [dynatrace-oss/dynatrace-monitoring-as-code#128]
Common feedback about Monaco is that people don't always know how to get started with the folder structure.

A `monaco init` command should be available that creates:

- Sample environments.yaml file
- Project directory
- For each supported config type, a folder should be created with a base yaml in there
- After the command executes it should print the exact command needed to apply that project

**Comment by Dynatrace-Adam-Gardner** [comment]
Would empty files be OK inside the folders? If so, I have some code.

**Comment by kristofre** [comment]
@Dynatrace-Adam-Gardner this is great stuff! For the yaml file, do you have the base structure there as well, something like this:
`config:
  - application: "application.json"

application:
  - name: "application-one"`

That would make it super easy.
If then that application.json also exists, all the user has to do is paste in the json body from the api explorer and they are good to go!

**Comment by Dynatrace-Adam-Gardner** [comment]
Done, this now creates a YAML file with content like:

```
config:
- alerting-profile: alerting-profile.json
alerting-profile:
- name: alerting-profile-one
```

**Comment by kristofre** [comment]
From the above it is not clear if it creates a sample `environments.yaml` as well?

**Comment by Dynatrace-Adam-Gardner** [comment]
It doesn't yet, but I'll add it

**Comment by Dynatrace-Adam-Gardner** [comment]
This is now complete. It generates files and folders for all APIs returned by the `api.NewApis()` which references the `apiMap` in `/pkg/api/api.go` so new APIs will automatically get folders and content.

One important note: You must delete folders that you're not using otherwise monaco will error.

Perhaps it's worth ignoring blank files? I'll start a new discussion for this.
