### ISSUE TITLE
Unable to use variables within curly brackets

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#13]
Defining a variable in JSON template within `{}` (without whitespaces) throws an error. At the moment only possibility it to define whole string in yaml which could be a bit cumbersome. This is e.g. needed if defining http monitor with credentials:
```
Api-Token {{{ .apiTokenId }}|token}
```

**Comment by baumgarb** [comment]
I believe you only need to tweak your template a bit. What is the expected output in your assuming the **apiTokenId** is **ABC123**? 

If the expected output is 

```
Api-Token {ABC123|token}
```

then you can simply achieve this by changing your template to

```
Api-Token {{ print `{` .apiTokenId `|token}` }}
```

If that doesn't help can you pls provide a stripped-down example of your YAML, JSON and the expected output?

**Comment by baumgarb** [comment]
@tatomir146 not sure if you saw my previous comment / question, but does that solve your problem? Otherwise it would be great if you could provide some more information as mentioned in the previous comment.

**Comment by tatomir146** [comment]
Thanks @baumgarb
