### ISSUE TITLE
Validation failing with monaco 1.2.0 but works with older releases

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#138]
**Describe the bug**
If running dry run validation fails with 
`2021-01-27 07:55:14 ERROR Validation of *** failed with error Id 'general/alerting-profile/config-id' was not available. Please make sure the reference exists.
`
This reference definitely exists. Running same validation with `monaco 1.1.0` works fine.

**How to reproduce**
Run validation on internal configuration repository using old CLI

**Expected behaviour**
Validation shouldn't fail

**Environment (please complete the following information):**
 - OS: testen on linux and mac
 - Tool version 1.2.0

**Comment by kristofre** [comment]
I noticed the same thing when validating a project that has dependencies to another project.
The issue does not affect project validation where there are no external dependencies. 

The way to go around it at the moment is to add a trailing slash to your projects folder, for example:

`monaco -v -dry-run -e=envs.yaml -p=project-one projects`

should become

`monaco -v -dry-run -e=envs.yaml -p=project-one projects/`

I still believe that this is a regression from v1.1.0 that should be addressed.
