### ISSUE TITLE
Monaco automatically deletes configurations in Dynatrace when removed from Monaco project

### ISSUE THREAD

**Issue by kristofre** [dynatrace-oss/dynatrace-monitoring-as-code#148]
I believe this ties into https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/16 as well, but wanted to make a separate feature request for it.

Monaco should have a mode where it is running as "single source of truth" for configuration, in a true GitOps model.
This means that when a configuration is removed from a centralised Monaco repo, upon the next Monaco run this config should also be removed from Dynatrace.

Since Monaco does not keep a state, one solution could be that Monaco retrieves a list of all configurations (e.g. Applications). After a successful run of applying configuration, it does a diff between what the desired state is (in Monaco config repo) and the current state (in Dynatrace). What is extra in Dynatrace should be removed.

This should probably not be the defacto standard operating mode of Monaco, but it should be an option controlled either by a flag or an environment variable.

**Comment by 163a** [comment]
My opinion on this is that you would need to implement this in a way that Monaco becomes aware of an centralised repository to compare those diffs.
The other factor is having Monaco "automatically" include those manually added configurations, so that there is a synchronisation. Maybe this is better suited to another tool?

**Comment by julieallard** [comment]
That is exactly what we need. This would allow Monaco to clean up any manual changes in the UI because people are not supposed to make manual changes. That would allow us to enforce that everyone makes config changes via pull requests.

**Comment by tatomir146** [comment]
I think we already had discussion about this some time ago but storing the state locally would complicate the things a bit. To properly implement this, support in product would also be needed. But, there is actually a way of making this work:
- store all configuration in repo (monaco already overwrites everything)
- remove permission from users so they can't do any unwanted changes
- (optionally) implement 4 eyes principle on adding config to the repo
