### ISSUE TITLE
Applying, Deploying a specific source configuration type to one or more environments

### ISSUE THREAD

**Issue by leonvzGit** [dynatrace-oss/dynatrace-monitoring-as-code#154]
**Is your feature request related to a problem? Please describe.**
Given a projects folder I created from downloading the configuration from 3 different environments in the environments.yaml file:
root/
  CentralDEV/
    alerting-profile/
    management-zone/
    dashboard/     
  CentralTEST/
    alerting-profile/
    ... 
  CentralQA/
    ...    
environments.yaml
 
Given the following command:
monaco deploy --environments=environments.yaml -specific-environment="CentralDEV" -p="CentralTEST/alerting-profile" --dry-run
 
There are no configurations being picked up to apply on CentralDEV
 
Does this mean if I want to export a specific configuration type(in this case alerting profile) from a single environment to another, I would have to create a project directory containing only the configuration type folder eg alerting profile?

**Describe the solution you'd like**
I would like the -p flag to accept the configuration type folder eg project/configuration-type, or a new flag to be introduced for a configuration-type that you want to apply. So that I can use exported configuration and sync specific configuration types from downloaded environments. This ties into the download command having the flag --downloadSpecificAPI. I would like to use a similar flag when deploying.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by didiladi** [comment]
@leonvzGit yes, you are right. In this case you would have to create a separate project with just the alerting profile in it.

The folder "alerting-profile" is treated as a set of configurations - its not a project.

@dynatrace-oss/mac-maintainers might be a good idea to offer a param to deploy just a single configuration-type (e.g. alerting-profiles).
