### ISSUE TITLE
Add support: Credential Vault

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#174]
Add support for `credential-vault`.

Please assign to me as I have the code ready. (PR #175)

**Comment by Dynatrace-Adam-Gardner** [comment]
This is blocked because the early adopter credential vault API isn't idempotent. `n` executions of monaco results in `n` different credentials.

**Comment by didiladi** [comment]
@Dynatrace-Adam-Gardner I corrently don't see why this shouldn't work with monaco. The API fulfills our criteria for an "[easy-to-add-api](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/docs/how-to-add-a-new-api.md)": https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/credential-vault/

For troubleshooting, can you apply a credentials-vault config and use the `MONACO_REQUEST_LOG` env var and post the log file here?

e.g.:
```
MONACO_REQUEST_LOG=requests.log ./monaco ...
```

**Comment by Dynatrace-Adam-Gardner** [comment]
This happens after the first run and on subsequent runs it stays like this. I never see a `PUT`.

```
url: https://abc123.live.dynatrace.com/api/config/v1/credentials
method: GET
==========
url: https://abc123.live.dynatrace.com/api/config/v1/credentials
method: POST
content:
{"description":"Sample set of credentials for API documentation","name":"Sample Credentials","ownerAccessOnly":"true","password":"1234abcd","scope":"SYNTHETIC","type":"USERNAME_PASSWORD","user":"foo"}
==========
```

**Comment by Dynatrace-Adam-Gardner** [comment]
Figured it out. I needed to add `propertyNameOfGetAllResponse: "credentials",`

**Comment by didiladi** [comment]
Yes, the `propertyNameOfGetAllResponse` is a new property, which needs to be set for some APIs. In case you missed it - we ramped up on the documentation for adding new APIs recently :muscle:: 

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/docs/how-to-add-a-new-api.md
