### ISSUE TITLE
[Grouper/Epic] Download Functionality problems and improvements

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#179]
Used internal env to test download functionality.

**Describe the bug**
Various things which should be improved by download functionality:
- remove "metadata" from JSON, no need to have this 
- syntheticLocations are empty `config: []`
- yaml formatting - no new lines used, making yaml files hard readable
- yaml: quoting values makes file better readable in IDEs
- main.go: downloadSpecificAPI should be either renamed to `download-specific-api` to keep consistency or even better to `specific-api` as it's a part of download command
- main.go: `p` alias used for `downloadSpecificApi` > not really intuitiv 
- main.go: help for download functionality tells `Yaml file containing environment to deploy to` - `deploy` should be renamed to `download`
- download.go: multiple `enviroments` typos
- IDs should be stripped eg: alerting-profile "mzId": "-6221876622438591000" 
- verbose prints out e.g. nil as string  `DEBUG getting detail {... Cl_ES %!s(*string=<nil>)}`
- built in extensions are also downloaded: ruxit.python.redis:slave_state:unsynchronized Redis Slave unsynchronized
- if there are multiple dashboards with same name then something like this is generated:
```
config:
- Home: Home.json
- Home: Home.json
- Home: Home.json
- Home: Home.json
Home:
- name: Home
- name: Home
- name: Home
- name: Home
```

**Comment by kristofre** [comment]
Not sure if I agree with 

> remove "metadata" from JSON, no need to have this

Usecase is as follows: what if I download from environment/cluster X (let's say non-prod) that is on version a and I want to apply that config to environment/cluster Y (production) that is on version b and there is a difference in API behaviour. The meta data of the version would allow us to process that properly

**Comment by diegorqc** [comment]
about the yaml formatting, we will have to look for an different parser from golang struct to yaml, the default one is quite strict in the convention for formatting https://github.com/go-yaml/yaml/issues/556. We will have to create custom formatters to get quoting and line breaks for certain blocks.

**Comment by tatomir146** [comment]
> Not sure if I agree with
> 
> > remove "metadata" from JSON, no need to have this
> 
> Usecase is as follows: what if I download from environment/cluster X (let's say non-prod) that is on version a and I want to apply that config to environment/cluster Y (production) that is on version b and there is a difference in API behaviour. The meta data of the version would allow us to process that properly

But is there any value in saving this into repository? If the idea is to use download functionality to pull and store config repo ready configuration, then this configuration should also work with different cluster versions. If the main concern is validation in case of failing updates (to another environment), then there are other plans in verifying configuration compatibility, not through metada.

**Comment by cvidler** [comment]
Adding to this issue at it seems relevant, happy to raise a new issue if more appropriate.

- app-detection-rule output of the download command, only includes one rule per application, if there's more than one rule, the others are ignored - not in the .json files.

Testing on a customers environment (hoping to use monaco to migrate all config from an environment into another), 25 Web Applications, the UI reports 36 app-detection-rules, only 25 are present in the JSON files.

(using version 1.4.0).

**Comment by kristofre** [comment]
> Adding to this issue at it seems relevant, happy to raise a new issue if more appropriate.
> 
> * app-detection-rule output of the download command, only includes one rule per application, if there's more than one rule, the others are ignored - not in the .json files.
> 
> Testing on a customers environment (hoping to use monaco to migrate all config from an environment into another), 25 Web Applications, the UI reports 36 app-detection-rules, only 25 are present in the JSON files.
> 
> (using version 1.4.0).


Some more meat around this:
We had a (DT Product) issue when trying to create multiple app detection rules for the same app using the API.
That was resolved, but only for newly created ones starting with 210.
But for the ones created before that we are merging them together and thus not applying them all:
```yaml
config:
- Webadmintools: Webadmintools.json
- Webadmintools: Webadmintools.json
- Webadmintools: Webadmintools.json
- Webadmintools: Webadmintools.json
- Webadmintools: Webadmintools.json

Webadmintools:
- name: Web admin tools
- name: Web admin tools
- name: Web admin tools
- name: Web admin tools
- name: Web admin tools

```

**Comment by diegorqc** [comment]
another issue for the custom service download needs to remove rule id and method rule Id to allow the deploy process to be transparent for the user.

**Comment by evanderbent** [comment]
Another issue is in application-web, "identifier" is not stripped blocking a re-upload.

**Comment by UnseenWizzard** [comment]
open sub tasks to be handled with v2
