### ISSUE TITLE
INFO verbose logging

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#18]
We would like to see a more verbose logging than currently is the case.

It would be interesting to see:
- API call made
- Response code

**Comment by robertjahn** [comment]
Yes I found that current `verbose` flag is not helping me see issues.  I have a config now that passes validation and there are not errors reported by monaco, but the config does not make it to DT.  So I up-vote this issue so we can have better ability to review and triage things.

**Comment by Everman** [comment]
Agree, now when you download configs but are missing token access rights no warning is given but you do end up with yaml files that are unusable.

**Comment by kristofre** [comment]
I believe this is covered by https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/194 and we can close this one

**Comment by patrickpichler** [comment]
Fixed with #219
