### ISSUE TITLE
Error for custom metrics with no condition marked with [Service property]

### ISSUE THREAD

**Issue by anton-freyberg** [dynatrace-oss/dynatrace-monitoring-as-code#183]
**Describe the bug**
For calculated service metrics created via the multidimensional analysis, topological filters are not required. When deploying such metrics, I get an error saying such a filter needs to be applied (this is the same error I would get when creating the metric in the settings). 
![image (10)](https://user-images.githubusercontent.com/71510895/108055719-a4d43f80-7050-11eb-9604-0a6c74f3df87.png)
![image (11)](https://user-images.githubusercontent.com/71510895/108055720-a6056c80-7050-11eb-9c54-c4f03bbf2d33.png)

**How to reproduce**
-download a metric created with multidimensional analysis
-delete it in the UI and try deploying it

**Expected behavior**
deployment without errors

**Log output**

[20210216-102115.log](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/files/5988191/20210216-102115.log)

**Environment (please complete the following information):**
 - OS: Win 10
 - Tool version 1.3.1

**Comment by UnseenWizzard** [comment]
Hi @anton-freyberg , 

> this is the same error I would get when creating the metric in the settings

Do I understand correctly that this issue is not monaco specific, but a general mismatch between creation of the metrics from a specific Dynatrace screen and creation via the Settings or API?

**Comment by anton-freyberg** [comment]
yes, you are correct, this is an API issue. Same error comes with the API explorer. I will close this and contact the API team. Thanks!
