### ISSUE TITLE
README.md contains missing text for request-naming-service

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#187]
`request-naming` should be `request-naming-service`

**Comment by 163a** [comment]
Made a fix for this but no permission to push the new branch and open pull request.

```git push --set-upstream origin bugfix/187/fix-readme-request-naming-service
ERROR: Permission to dynatrace-oss/dynatrace-monitoring-as-code.git denied to 163a.
fatal: Could not read from remote repository.
```

**Comment by tatomir146** [comment]
@163a thanks for reporting and fixing this. You can fork this project, do changes, and then open PR.

**Comment by 163a** [comment]
@tatomir146 pull request opened: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/pull/236

**Comment by 163a** [comment]
Closed, as https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/pull/236 has been merged.
