### ISSUE TITLE
Monaco Documentation of Output

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#188]
**Is your feature request related to a problem? Please describe.**
Monaco structure is logic for users but not immediately digestable to non-technical users.

**Describe the solution you'd like**
Given a set of monaco configuration projects, monaco should be able to self produce a documentation listing what configuration will be applied.

For example:

Your monaco folder contains 2 projects:
- ProjectA
- ProjectB

`ProjectA` contains the following configuration:

- 1x Auto tag rule called `myTagRule`
- 1x Management zone called `myZone`
- 1x Alerting profile called `alertProfile`
- 1x Problem notification called `alert` which references the `alertProfile` alerting profile.

**Describe alternatives you've considered**
N/A

**Additional context**
The output format of this tool (PDF, Word doc, Markdown) is up for discussion.
The format of the output (text heavy or more visual with linked graphics is up for discussion.

@163a as discussed.

**Comment by UnseenWizzard** [comment]
Do understand correctly that this request is to generate more verbose output of what is being applied? 

Could this be something that would generally make sense to add - in addition to the current simple logging of which projects are being applied/validated and the full verbose log of deployments?
