### ISSUE TITLE
Don't delete configs if apply didn't work

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#20]
Currently, the tool deletes the configs in the `delete.yaml` file independently of the success of the prior applying of configs.

If the apply fails (for any config) we should skip the delete.

**Comment by JACONDE** [comment]
I think it will be worth to have a delete.yaml per project, instead of a file for the overall project folder.

**Comment by didiladi** [comment]
@JACONDE, yes that completely makes sense. There is already a ticket for that: #16

**Comment by didiladi** [comment]
@neonalps fixed this one in #79 -> Moving this to done
