### ISSUE TITLE
RFE: Add Option for Proxy

### ISSUE THREAD

**Issue by Dynatrace-Tomislav** [dynatrace-oss/dynatrace-monitoring-as-code#232]
Request for enhancement: Add optional parameter to provide proxy when running Monaco. 
For example: `--proxy=<proxy-server>:<port>`

That is for environments where calling the DT API URL (DT SaaS or DT Managed) is only possible or allowed via proxy.

**Potential workaround:** 
I have also tried the option to call the DT REST API over an Environment ActiveGate:
Example for DT SaaS: In environments.yaml: Instead of `https://<tenant-ID>.live.dynatrace.com` as `env-url` ---> use `https://<Env-AG>:9999/e/<tenant-ID>/` as `env URL`

By default, ActiveGate uses a self-signed certificate (authentication certificate to all connecting clients). Hence, Monco fails with below error message (example below for creating auto tags via Monaco):

`ERROR HTTP Request failed with Error: Get "https://<ActiveGate-IP>:9999/e/<environment-ID>/api/config/v1/autoTags": x509: certificate signed by unknown authority`

One could configure a custom SSL certificate on the ActiveGate as per page [here](https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-activegate/configuration/configure-custom-ssl-certificate-on-activegate/). However, it would be easier and quicker to provide an optional proxy parameter in more restrictive environments.

**Comment by patrickpichler** [comment]
Hi, this should already be possible be setting the `HTTPS_PROXY` environment variable.
