### ISSUE TITLE
Support to add additional APIs by specifying them via program argument

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#24]
We need to have a mechanism for specifying additional APIs which are present at Dynatrace, but which we haven't included in the `api.go` currently. `api.go` contains the APIs which are already well-tested. However, there are a lot of other APIs which we didn't need before - so we never added them to the tooling.

In order to support these APIs, we want to perform the following actions:

- add a program argument for specifying a path to a `yaml` file
- the `yaml` file is a simple list, which specifies is in the following format:
```
apis:
  - some-new-api: path-to-api
  - some-new-api-2: path-to-api-2
```
- these APIs should be usable in addition to the one listes in `api.go`

**Comment by UnseenWizzard** [comment]
As this was a Dynatrace internal need and monaco now has full internal development support as well as a concept to internally offer and test release candidate versions, I am closing this enhancement idea. 
Please reopen in internal issue tracking if you still think this is needed at the moment.
