### ISSUE TITLE
Downloading Web Application config creates both application and application-web folder

### ISSUE THREAD

**Issue by kristofre** [dynatrace-oss/dynatrace-monitoring-as-code#271]
**Describe the bug**
When I use the download functionality to get Web Application configuration from Dynatrace, it creates both an `application` and `application-web` folder with the same contents

**How to reproduce**
execute a download against an environment that has a web application defined

**Expected behavior**
It should only create the `application-web` folder

**Comment by diegorqc** [comment]
Just to add more information to this bug, currently there is no way to identify inside monaco what configs would be deprecated, or which ones should belong to an specific version of monaco. We can have this be a special case and hardcode something against "application" or we might have to create an additional property to identify apis to be deprecated

**Comment by tatomir146** [comment]
This will be solved with monaco 2.0 as then we are going to deprecate application config.
