### ISSUE TITLE
Certificate Error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zion002** [dynatrace-oss/dynatrace-monitoring-as-code#287]
We have a Dynatrace implementation with our own signing authority. While trying to use the Monaco, we are getting error "x509: certificate signed by unknown authority"

**How to reproduce**
Use a Dynatrace implementation with Own Signed Certificate. It should not be certificates signed by Dynatrace and then try to download the configuration (./monaco download --envrinoments=<env>.yaml

We are getting error "509: certificate signed by unknown authority"

**Log output**
509: certificate signed by unknown authority

**Environment (please complete the following information):**
 - OS: Linux
 - Tool version : Monaco version 1.5.0

**Additional context**
Need to know the way that allow Monaco to trust the certificate (custom certificate) so that we can able to download our configurations.

**Comment by tatomir146** [comment]
Hi @zion002, please make sure to check discussion before opening up a ticket. This is already answered in #291. Basically, we don't support self signed certificate, and if you need to support these, then it should be added to the OS trust store.
