### ISSUE TITLE
Support connecting a kubernetes cluster in tooling

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#3]
See: https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/installation-and-operation/further-integrations/connect-your-kubernetes-clusters-to-dynatrace/

There is an API for doing that. Add the necessary configs in the infrastructure project in the self-monitoring tooling.

**Comment by didiladi** [comment]
This was already done before open-sourcing the tooling -> Moving this to done.
