### ISSUE TITLE
Request attributes should compared against existing record

### ISSUE THREAD

**Issue by juliusloman** [dynatrace-oss/dynatrace-monitoring-as-code#300]
**Describe the bug**
When deploying a monaco project having request attributes, request attributes are always replaced (the same configuration is pushed to Config API). For Dynatrace project where request attributes are based on method arguments, will stop being collected until a restart of those processes is performed - in case real-time updates are not enabled. As Dynamic updates are typically disabled in production environments for sanity reasons, redeploying the same request attribute will result in request attribute collection being stopped. Details in SUP-71140.

**How to reproduce**
Steps to reproduce the behaviour:
- a project with request attribute based on method arguments (Java for example)
- Dynatrace environment with real-time updates disabled (default setting)
- deploy configuration - observe request attributes collection being stopped for the request attribute

**Expected behavior**
- monaco should check if the definition of request attribute matches the current deployed version
- monaco should upload the new definition only if there is a change in the configuration

**Log output**
- N/A

**Environment (please complete the following information):**
- Monaco 1.5.0

**Additional context**
Based on the support ticket, https://support.dynatrace.com/supportportal/browse/SUP-71140 , a new ruleset for instrumentation is created each time a request attribute definition based on method arguments is saved.

**Comment by tatomir146** [comment]
Hi @juliusloman, thanks for reporting this issue. This actually isn't an issue with monaco as monaco is always updating existing resources (not recreating) using PUT method. There was a BUG in product which is solved with v1.215 release where process restart is not needed anymore.
