### ISSUE TITLE
Missing Application Detection Rules

### ISSUE THREAD

**Issue by mark-dt** [dynatrace-oss/dynatrace-monitoring-as-code#306]
**Describe the bug**
When downloading the configuration if an application has multiple detection rules then only one will be downloaded, I think the files are being overwritten.
In the YAML file for the detection rules we see 2 entries, so monaco is detecting them correctly but somehow overwriting one (?)

**How to reproduce**
- create multiple detection rules for same application
- download config
- check the detection rules for the application with multiple detection rules

**Expected behavior**
I would expect to see all application detection rules for all defined applications

**Log output**
N/A

**Environment (please complete the following information):**
 - OS: Win 10
- monaco 1.5.2

**Comment by tatomir146** [comment]
@diegorqc can you please have a look here?
