### ISSUE TITLE
Duplicate Notification Names cause overwrite

### ISSUE THREAD

**Issue by andymanning** [dynatrace-oss/dynatrace-monitoring-as-code#327]
**Describe the bug**
Dynatrace allows notifications with the same name. eg.
NotificationFoo (of type email)
NotificationFoo (or type pagerduty) 

but when these are downloaded using Monaco only one appears. i.e
/notification/NotificationFoo.json 

I suspect that both are actually downloaded but the second one overwrites the first one.

**How to reproduce**
1. Create two notifications with the same name using the Dyntrace GUI
2. Run the tool 
`NEW_CLI=1 monaco download -e=environments.yaml -s=prod --downloadSpecificAPI notification`

**Expected behavior**
The second file is download with a prefix such as (1) so /notification would contain
NotificationFoo.json
NotificationFoo(1).json

**Log output**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS 
 - Tool version: v1.5.3

**Additional context**
N/A

**Comment by tatomir146** [comment]
Hi @andymanning! We don't think it's a good practice to have multiple resources having the same name, and if monaco detects 2 resources sharing same name it will fail during validation. Name is the identifier monaco uses to detect if configuration already exist on the given tenant. I would strongly advise to rename one of the notification and prevent collision.
