### ISSUE TITLE
YAML Parsing Limited to Basic Types

### ISSUE THREAD

**Issue by jenrsparks** [dynatrace-oss/dynatrace-monitoring-as-code#341]
**Describe the bug**

Complex or nested structures are not accurately parsed and result in the error "{file} could not be parsed: cannot convert YAML" even though it is valid YAML.

**How to reproduce**
Example Configuration File "notification.yaml":

```
config:
- Email-Sample: Email-Sample.json

Email-Sample:
- name: Email - Sample
Email-Sample:
  stage:
  - skipDeployment: "true"
  prod:
  - tenant: Prod
  - profile_id: 08166fb9-01b4-48f0-b1d2-57d7c8a88310
```

**Expected behavior**

The file should parse successfully as a valid notification.yaml file. The above sample configuration works when flattened to key/value pairs of simple strings as values:
```
config:
- Email-Sample: Email-Sample.json

Email-Sample:
- name: Email - Sample
Email-Sample.stage:
- skipDeployment: "true"
Email-Sample.prod:
- tenant: Prod
- profile_id: 08166fb9-01b4-48f0-b1d2-57d7c8a88310
```

**Log output**

```
e084531@GH-827ZLQ2 MINGW64 ~/oss/dynatrace-monitoring-as-code/cmd/monaco ((v1.5.3))
$ go run main.go deploy --dry-run --environments=/c/Users/e084531/Documents/repos/dynatrace_configuration/test/environments.yaml -s=prod /c/Users/e084531/Documents/repos/dynatrace_configuration/
You are using the new CLI structure which is currently in Beta.

Please provide feedback here:
  https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/45.

We plan to make this CLI GA in version 2.0.0

2021-06-07 12:53:09 INFO  Dynatrace Monitoring as Code v1.5.3
2021-06-07 12:53:09 FATAL YAML file C:\Users\e084531\Documents\repos\dynatrace_configuration\test\notification\notification.yaml could not be parsed: cannot convert YAML
exit status 1
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Tool version: v1.5.3

**Comment by patrickpichler** [comment]
Hi, thank you for the bug report!

The issue here is that we parse the yaml as basically a map of string to structs.
I'm not 100% sure if changing this to also allow the thing you describes, is worth
the complexity this would bring. 

What exactly is your use case you are trying to solve by defining the same config
multiple times?

**Comment by patrickpichler** [comment]
After a short sync with the other maintainers, we concluded that we probably aren't going 
to support this. 

Hence I'm closing this issue.

**Comment by jenrsparks** [comment]
@patrickpichler , Apologies for missing your prior message! When dealing with a lot of environments, it was difficult to visually perceive that each entry was environment-specific versus the common items, so I'd attempted to gain some better display by using YAML structure, and incorrectly assumed it was intended to support YAML given the yaml filename extension.

Thanks for following up!
