### ISSUE TITLE
Various timing issues between configs

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#349]
**Describe the bug**
We currently have a timing issue between calculated service metrics and SLOs. When an SLO depends on a calc service metric, `monaco` correctly creates the calc service metric first. However, as soon as the SLO config is applied, the API validation kicks in with the following error:

```
[2021-06-22T07:48:01.047Z]     Response was: {"error":{"code":400,"message":"Validation failed for 1 Validators.","constraintViolations":[{"path":"builtin:monitoring.slo/0/metricNumerator","message":"Given property 'metricNumerator' with value: 'calc:service.<snip>' violates the following constraint: Metric selector for numerator is invalid..","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config:<snip>.json
```

It complains that it can't find the calculated service metric. This error just happens when the environment creates both configs for the first time.

**How to reproduce**
Add a SLO config depending on a calculated service metric:

```
{
  "enabled": true,
  "name": "{{ .name }}",
  "description": "Measures the ratio of service cally below {{ .milliseconds }} milliseconds. (# of service calls < {{ .milliseconds }} milliseconds / # of total service calls)",
  "status": "WARNING",
  "error": "NONE",
  "useRateMetric": false,
  "metricRate": "",
  "metricNumerator": "{{ .calculatedServiceMetricId }}",
  "metricDenominator": "builtin:service.requestCount.server",
  "target": {{ .target }},
  "warning": {{ .warning }},
  "evaluationType": "AGGREGATE",
  "timeframe": "-1h",
  "filter": "type(\"SERVICE\"), entityId(\"{{ .meId }}\")"
}
```

```
config:
  - responseTimeLessThan250ms: "response-time-less-than-X-ms.json"

responseTimeLessThan250ms:
  - name: "Response Time less than 250ms"
  - calculatedServiceMetricId: "/service/calculated-metrics-service/responseTimeLessThan250ms.id"
  - milliseconds: "250"
  - target: "95"
  - warning: "96"
  - meId: "<snip>"
```

**Expected behavior**
`monaco` should wait with applying the SLO until the calc service metris is fully present at the environment. Probably, some kind of retry mechanism is needed here.

**Comment by kristofre** [comment]
The same behaviour exists with Applications and Synthetic Monitors. If in one monaco run you create an application and then reference it in a synthetic test, Monaco will fail stating the Application does not exist. A subsequent run would be successful.

**Comment by robertjahn** [comment]
I have a similar issue with SLOs that use MZ Filter `"filter": "mzName(\"{{ .mzname }}\"),type(\"SERVICE\")"`.  monaco log will show `Response was: {"error":{"code":400,"message":"SLO validation failed with 1 error(s):\nGiven filter is invalid."}}, responsible config: monaco-files/projects/workshop/slo/monolith-slo.json`.    If you want a new issue for this, let me know.

**Comment by joostvz** [comment]
@kristofre We just experienced this issue with the combination of a new Application and new Synthetic Monitors like you describe. Will this issue be fixed in a future version? This sounds like a general retry mechanism which should be added to Monaco which waits untill all dependencies are created.

**Comment by didiladi** [comment]
Another timing issue: synthetic tests + synthetic credential vault. The error is:
```
11:12:56  2021-11-25 10:12:55 ERROR 	Id '<project>/credential-vault/<referenced-id>' was not available. Please make sure the reference exists.
```

**Comment by didiladi** [comment]
I'll take a look at this issue next and try to find a generic solution to the problem. As of now we have some rudimentary retry mechanism based on whitelisting in place: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/pkg/rest/config_upload.go#L85-L107

The goal would be to detect automatically if a retry is necessary. One possible implementation: When the upload of a config fails:
* We check whether dependencies of this config were just being created (monaco performed a `POST`).
* If no: return the error to the user
* If yes: Check if these dependencies already exist by performing a `GET` request and possibly start a retry handling until the `GET` returns the wanted config (or times out). When it does: retry the failing config update.
