### ISSUE TITLE
No Downloaded Configuration

### ISSUE THREAD

**Issue by rodel-ooh-media** [dynatrace-oss/dynatrace-monitoring-as-code#376]
**Describe the bug**
Using monaco client to download the existing configuration didn't download any

**How to reproduce**

- environments files
```
dynatrace:
    - name: "dynatrace"
    - env-url: "{{.Env.DT_URL}}"
    - env-token-name: "DT_TOKEN"
```
- Flags used to execute tool
```
$ monaco download --downloadSpecificAPI alerting-profile,dashboard --environments=environments.yaml
```

**Expected behavior**
Got a lot of Alerting Profiles (and others) created through the console. I need to download them to do a weekly refresh.
Expecting downloaded configurations.

**Log output**
```
$ monaco download --downloadSpecificAPI alerting-profile,dashboard --environments=environments.yaml
You are using the new CLI structure which is currently in Beta.

Please provide feedback here:
  https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/45.

We plan to make this CLI GA in version 2.0.0

2021-07-06 21:40:42 INFO  Dynatrace Monitoring as Code v1.6.0
2021-07-06 21:40:42 INFO  Creating base project name oohmedia
2021-07-06 21:40:42 INFO   --- GETTING CONFIGS for alerting-profile
2021-07-06 21:40:42 INFO  No elements for API alerting-profile
2021-07-06 21:40:42 INFO   --- GETTING CONFIGS for dashboard
2021-07-06 21:40:42 INFO  No elements for API dashboard
2021-07-06 21:40:42 INFO  END downloading info dynatrace

```

**Environment (please complete the following information):**
 - OS: linux and/or mac
 - monaco - 1.6.0

**Comment by Dynatrace-Adam-Gardner** [comment]
Hi Rodel. This works for me on Windows monaco v1.6.0.

Are you sure your API token has the right permissions? See [this page](https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/configTypes_tokenPermissions)

![image](https://user-images.githubusercontent.com/13639658/125028036-a919fb80-e0ca-11eb-8d88-c0f17f37edfe.png)

**Comment by UnseenWizzard** [comment]
Hi @rodel-ooh-media was there a problem with the API token permissions as @Dynatrace-Adam-Gardner suggests? 

I will close this issue as stale/not an issue, unless this still is a problem for you and not related to permissions
