### ISSUE TITLE
Improve help text

### ISSUE THREAD

**Issue by patrickpichler** [dynatrace-oss/dynatrace-monitoring-as-code#40]
When help text output is not really helpful, as it doesn't show all possibilities how 
to execute monaco.

For example there is no info at all, how to specify which folder the project configurations
are in.

**Comment by tatomir146** [comment]
@patrickpichler at least it's documented in README:

```
For deploying a specific project inside a root config folder, the tool could be run as:

`monaco -p="project-folder" -e="environments.yaml" projects-root-folder`
```

**Comment by patrickpichler** [comment]
Yes, but if you ask me it would be really beneficial to also have it in the help text.

**Comment by Dynatrace-Adam-Gardner** [comment]
Referencing #54 here to include a note about API permissions near the top of the README.
