### ISSUE TITLE
Fix documentation mentioning environment-url instead of env-url

### ISSUE THREAD

**Issue by patrickpichler** [dynatrace-oss/dynatrace-monitoring-as-code#41]
The documentation mentions in some places `environment-url` when in reality this
configuration key is called `env-url`.

**Comment by neox5** [comment]
I'm reviewing the whole project and I can improve the docs if this is desirable? : )

**Comment by patrickpichler** [comment]
Hi there,

This would be awesome!
Thank you!

**Comment by neox5** [comment]
Added #49
