### ISSUE TITLE
Enhancement request for Support anomaly-detection rules for Infra/DB/etc....

### ISSUE THREAD

**Issue by JACONDE** [dynatrace-oss/dynatrace-monitoring-as-code#48]
It will be great to be able to automate also anomaly detection rules for other items like Infra, DB, applications, etc....

**Comment by tatomir146** [comment]
Hi @JACONDE, thanks for creating this request. As Dynatrace Monitoring as Code is an open source project, we would be very happy to have external contributors, and I would like to encourage you to implement this. Adding new API support is as simple as adding it's definition to `/pkg/api/api.go` and defining additional test for it in `/cmd/monaco/test-resources/integration-all-configs/project`. We would be very happy to get your PR.

**Comment by UnseenWizzard** [comment]
Hi @JACONDE. From version 1.8.0 upwards nearly all anomaly detection metric APIs - with the exception of Process Groups - are supported by monaco.
For details are https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/configTypes_tokenPermissions
