### ISSUE TITLE
Monaco does not find applicationID and creates duplicates application

### ISSUE THREAD

**Issue by Mrick06B** [dynatrace-oss/dynatrace-monitoring-as-code#483]
**Describe the bug**

I am having several problems with Monaco and I can't figure out what is causing them.
When I deploy an application, I systematically get an error: the application ID does not exist. 

However the application ID does exist! and I can see the application created in Dynatrace.
And yet at each execution (when Monaco generates this error), Monaco creates a new application (with the same name specified in the yaml but with an increment beside it).
Could you help me on this subject ? 
For information, I had this problem a few weeks ago, with the difference that before Monaco did not create a duplicate of the application. I just had to launch Monaco a few seconds later so that it would find the application ID.
Thank you!

The problem seems to come from the synthetic json file : 
ERROR \tFailed to update DT object 10_11_06 OCP (HTTP 400)!",
        "    Response was: {\"error\":{\"code\":400,\"message\":\"Unknown application(s): APPLICATION-XXXXXXXX\"}}, responsible config: monaco/deployments/PROD/10_11_06_OCP/synthetic-monitor/10_11_06_OCP.json",
 where it is specified:
"manuallyAssignedApps": [
"{{ .appID }}"
In the synthetic yaml:
- appID: "/application-web/defaultApp.id"

**How to reproduce**
See file attached.
monaco deploy  -e=./conf/environment_test.yaml ./deployments/PROD/10_11_07_OCP/

**Environment (please complete the following information):**
 - OS: Linux
 - Tool version 1.6.0
 
 
 I cannot attach the file..Below is an extract of the Monaco configuration

**application-web YAML**
config:
  - defaultApp: 10_11_07_OCP.json

defaultApp:
  - name: 10_11_07 OCP
  - ocp_name: 10_11_07 OCP PROD

**application-web JSON**
,
 "name": "{{.ocp_name}}",
 "realUserMonitoringEnabled": true,
 "sessionReplayConfig": {
  "costControlPercentage": 20,
  "enabled": true
 },
 
 **synthetic YAML**
config:
- default_http_monitor: 10_11_07_OCP.json
default_http_monitor:
- name: 10_11_07 OCP
- url: https://xxxxxxxxxxxx
- appID: "/application-web/defaultApp.id"

Synthetic JSON
 "manuallyAssignedApps": [
 "{{ .appID }}"
 ],
 "name": "{{ .name }}",
 "requests": [
  {   
   "name": "{{ .name }}",
   "sequenceNumber": 1
  }
 ],

**Comment by didiladi** [comment]
Hey @Mrick06B! On first glance I don't see anything wrong with your configuration - this should work. I'm currently in the process of trying to reproduce the issue - I'll send an update once I successfully reproduced the issue.

**Comment by didiladi** [comment]
Ok, found the issue while trying to reconstruct your example.

The problem in your configuration is that you use a different `name` in the `json` and in the `yaml` file of your application:

yaml: (`name` used by monaco is `10_11_07 OCP`)
```
config:
  - defaultApp: 10_11_07_OCP.json

defaultApp:
  - name: 10_11_07 OCP
  - ocp_name: 10_11_07 OCP PROD
```

json: (name is `ocp_name` -> `10_11_07 OCP PROD`):
```
{
    "name": "{{.ocp_name}}",
    "realUserMonitoringEnabled": true,
    "sessionReplayConfig": {
        "costControlPercentage": 20,
        "enabled": true
    }
    ...
}
```

To solve the issue, just change the json of the `application-web` to:
```
{
    "name": "{{.name}}",
    "realUserMonitoringEnabled": true,
    "sessionReplayConfig": {
        "costControlPercentage": 20,
        "enabled": true
    }
    ...
}
```

Background: `monaco` uses the `name` property defined in the json to look up the `id` of the config object (if it exists). If you now use a different name in the json and the yaml, you will store the config with one name (`10_11_07 OCP PROD`), but another name (`10_11_07 OCP`) will be used to determine if it was already stored.

I hope I could help you @Mrick06B :slightly_smiling_face:

**Comment by Mrick06B** [comment]
Hi All,

Thanks four help and your responsiveness !

@didiladi The yaml and json files are built dynamically from a CI/CD pipeline.
Depending on the template/variables sent to the playbooks, the json takes into account the .name or .ocpname.
In this example, only the .ocpname is used. (but indeed I should rename the variable {{.name}} with a more explicit name)

I have done other tests and I can't figure out what the problem is (I didn't have this behaviour before).

It looks like Monaco can't get the application it created and tries to create a new one..and loops, it doesn't find the new application either..very strange...).

**Comment by didiladi** [comment]
monaco relies on the fact that the variable is named `name` in the yaml. Is this the case in your configs @Mrick06B? If it isn't, it would explain the behaviour you describe.

**Comment by Mrick06B** [comment]
Mmm.
I have deleted the 
- ocp_name: {{ project }} {{ env | upper }}

Now in the template, I have only  :
defaultApp:
  - name: {{ project }} {{ env | upper }}

And I'm using now the {{ .name }}  (instead of {{ .ocp_name }} ) in the json and indeed it works ! 
Well..almost, I still have to launch the monaco 2 or 3 times to 'let it find' the application ID ( I will check if I do not have the same configuration in other yaml files)

I was thinking that if the  {{ .name }} is not used by the json file, there would be no impact...
Could you please explain to me why it should have an impact ?

And again..thank you :)

**Comment by Mrick06B** [comment]
@didiladi 

Sorry, I read your last message too quickly..

_Background: monaco uses the name property defined in the json to look up the id of the config object (if it exists). If you now use a different name in the json and the yaml, you will store the config with one name (10_11_07 OCP PROD), but another name (10_11_07 OCP) will be used to determine if it was already stored._

I understand now the issue.
Thanks for the support, I really appreciate.

**Comment by didiladi** [comment]
Cool @Mrick06B, glad that I could help :slightly_smiling_face:
