### ISSUE TITLE
'=' in env value is invalid

### ISSUE THREAD

**Issue by christophpe** [dynatrace-oss/dynatrace-monitoring-as-code#496]
**Describe the bug**
We defined a Jenkins Secret that contains a URL with an API key including the equals sign '='. This secret is defined in a Jenkinsfile and we wanted to then reference it in notifications.yaml.
Unfortunately this broke the build indicating that the secret cannot be found.

**How to reproduce**
- create a Jenkins secret that contains '='
- reference secret in Jenkinsfile
- reference env var from Jenkinsfile in a yaml file like    "{{ .Env.ENV_VAR_CONTAINING_URL }}"

**Expected behavior**
The secret (URL) being picked up correctly as an env value.

**Additional context**
[Related internal slack thread](https://dynatrace.slack.com/archives/C010YNQL570/p1638268088082400)

**Comment by AhmedEJ** [comment]
I can confirm the same issue is present when using a Jenkins `stringParam` text parameter that gets populated with a string that contains the `=` sign.
