### ISSUE TITLE
Monaco doesn't work with .yml ending

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#528]
**Describe the bug**
`.yml` and `.yaml` are valid file endings yet Monaco doesn't "see" `.yml` files.

**How to reproduce**
Create a config (eg. `auto-tag`) with a `tags.yml` file.

Monaco will not see the config
**Expected behavior**
Monaco parses the `.yml` file just like `.yaml`

**Comment by UnseenWizzard** [comment]
PR #529 merged - monaco will allow .yml as well - thanks for the contribution @Dynatrace-Adam-Gardner !
