### ISSUE TITLE
Unable to deploy SLO when new metric is also created with monaco

### ISSUE THREAD

**Issue by AH-ErikPost** [dynatrace-oss/dynatrace-monitoring-as-code#530]
**Describe the bug**
When creating a SLO through monaco that is based on a new custom metric (in the folder calculated-metrics-service) the deploy will fail because monaco will first try to create the SLO but the metric is not yet available resulting in a HTTP 400 with the message 'violates the following constraint: Metric selector is invalid'.

**How to reproduce**
- Define new SLO based on a new custom metric
- Define new custom-metric to be used in SLO
- Monaco deploy

**Expected behavior**
First the metric should be created since I think this is not depending on other things deployed by monaco, and after the metrics are deployed can the SLO's be deployed. I think a simple difference in deployment sequence is sufficient to solve the issue.

**Log output**
Response was: {"error":{"code":400,"message":"Validation failed for 2 Validators.","constraintViolations":[{"path":"builtin:monitoring.slo/0/metricExpression","message":"Given property 'metricExpression' with value: '(100)*(calc:service.bonus_request_count_response_time_2500:splitBy():percentile(75):auto:sort(value(percentile(75),descending)))/(builtin:service.keyRequest.count.total:splitBy())' violates the following constraint: Metric selector is invalid.

**Environment (please complete the following information):**
 - monaco version 1.6.0

**Additional context**
-

**Comment by UnseenWizzard** [comment]
Hi @AH-ErikPost sorry for the late reaction on this! 

How exactly is your SLO 'based on'  the new metric? 
monaco ensures upload in the correct order if you reference the configuration you depend on via monaco. If you do not do that, it is not aware that you're configurations depend on each other. 

See https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/yaml_config#referencing-other-configurations

If this is how you've configured things already this would be a bug in dependency resolution/sorting. 
If you have the calculated-metrics-service already referenced in the slo and this still does not work, please provide a minimal configuration as attachment so we can reproduce this. 

---

_As part of cleaning up monaco's backlog, I will close this ticket as resolved if you don't let me know this is still an issue within the next 10 days._
