### ISSUE TITLE
Unable to re-run app-detection-rule using Monaco.

### ISSUE THREAD

**Issue by Aditya-Sinha1990** [dynatrace-oss/dynatrace-monitoring-as-code#531]
**Describe the bug**
Unable to re-run app-detection-rule using Monaco.

**How to reproduce**
- environments files
- Yaml config
- JSON template
- Flags used to execute tool

**Expected behavior**
It should just pass as available and pass or update the resource in place with an updated value.

**Log output**

**Deployment to *** failed with error!**
2022-02-01 12:02:08 ERROR 	Failed to upsert DT object foo.bar.baz (HTTP 400)!
    Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"","message":"Given application detection rule duplicates rule 01111118-211f-4111-a111-a1111111111a","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config: project/app-detection-rule/template-app-detection-rule.json
2022-02-01 12:02:08 ERROR Errors during deployment! Check log!

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Tool version v1.5.0

**Additional context**

**Note:** - _**Getting Additional Info to update this issue to reproduce the behavior **_

**Comment by mdicss** [comment]
See also: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/293#discussioncomment-619795

**Comment by Laubi** [comment]
I investigated the issue and was able to reproduce it in version 1.5.0 as well as 1.8.1. 
The good news is: There is already a way to fix it, as we had several improvements over the last few versions.

**To fix the issue:**
* Update Monaco to at least version 1.8.0.
* Migrate the API from 'app-detection-rule' to 'app-detection-rule-v2'. [You can find detailed instructions in our documentation.](https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/Guides/deprecated_migration#dashboard-request-naming-service-app-detection-rule)
