### ISSUE TITLE
Enhance documentation - Token permissions

### ISSUE THREAD

**Issue by JACONDE** [dynatrace-oss/dynatrace-monitoring-as-code#54]
It may be worth to document the minimum API token requirements needed for creating the new Dynatrace config using this new "as code" tool

**Comment by Dynatrace-Adam-Gardner** [comment]
Good point and a question that will come up repeatedly. Explicitly specifying permissions will be impossible because it depends on which configurations you're pushing.

For example, creating synthetic locations and tests will require additional permissions than just pushing tag rules.

What we can and should do is add a note near the top of the readme about this.

**Comment by JACONDE** [comment]
Just an idea: you can add a type of table for the features implemented with token permissions:
alerting-profile: /api/config/v1/alertingProfiles --> Token permission: xxxxxx
aws-credentials: /api/config/v1/aws/credentials --> Token permission: xxxxxx

**Comment by CruzanCaramele** [comment]
I am in progress with this

**Comment by UnseenWizzard** [comment]
For synthetic locations is `Access problem and event feed, metrics and topology` really needed @CruzanCaramele ?

**Comment by JACONDE** [comment]
I think you are right... with Create and read Synthetic monitors and location should be enough. 
I will have a look tomorrow also to the rights required for the maintenance window and application creation and application detection rule.

**Comment by CruzanCaramele** [comment]
@UnseenWizzard @JACONDE yes , it is really needed for **GET**  getting  synthetic location(s)

 here is the complete list:



![image](https://user-images.githubusercontent.com/6834860/100421118-0a371680-3088-11eb-80c6-47e77aff0b27.png)

**Comment by UnseenWizzard** [comment]
cool stuff, thanks @CruzanCaramele !
That location permission reallys seems pretty odd though - seems worth discussing internally if that's actually how it **should** be!

**Comment by JACONDE** [comment]
I just did a test with the API permissions on the table and it works fine.
So, I think we are good to go updating the documentation
