### ISSUE TITLE
Upsert typo?

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#57]
Is this a typo? `upsert` should be `insert`?

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/389a293894d51515214afd7887687df1d6ead164/pkg/rest/config_upload.go#L32 and https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/389a293894d51515214afd7887687df1d6ead164/pkg/rest/config_upload.go#L78

**Comment by didiladi** [comment]
Its in fact not a typo. This method checks internally, if the config already exists (by resolving it via the name). If it does not exist, it performs a `POST` against the API, otherwise a `PUT`.
