### ISSUE TITLE
Error deleting resource when resource name contains slash character

### ISSUE THREAD

**Issue by kasarpolis** [dynatrace-oss/dynatrace-monitoring-as-code#586]
We use slashes in our management zone names.  Monaco throws an error when attempting to delete them.

Example:
delete.yaml 

```
delete:
- "management-zone/mz-name-part1/mz-name-part2"
```

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/70e6b4b6d8c4b53d3f6a5e3b36e59fde34ddfbb3/pkg/delete/delete.go#L89

**Comment by UnseenWizzard** [comment]
As the delete yaml always expects entries as `type/name` this should be simple to fix by splitting on the first `/` only
