### ISSUE TITLE
Problem with using flags

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#6]
If using flags without equals "=" there is a bug if specifying project parameter as latest:
`command... -p my_project`

2020/04/16 11:07:02 Project my_project does not exist!: stat my_project/my_project: no such file or directory

Following works:
`command... -p=my_project`

The last parameter gets interpreted as configuration root parameter

**Comment by patrickpichler** [comment]
This should be fixed by #100
