### ISSUE TITLE
Slashes can not be used in variables - Caused by current OS path-seperator handling

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#60]
**Describe the bug**
Monaco fails for synthetic tests when a variable uses special characters. However passing the same string directly via JSON works.

**How to reproduce**

```
my_config:
  - ua_string: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
```
and
```
{
...
  "script": {
    "configuration": {
      "userAgent": "{{ .ua_string }}"
    }
  }
...
}
```

Fails with (line 11 is the userAgent line):
```
Response was: {"error":{"code":400,"message":"Could not map JSON at 'script' near line 11 column 20"}}, responsible config: projects\baseconfig\synthetic-monitor\myfile.json
```

Whereas removing that YAML variable and pushing this, works just fine.

```
{
...
  "script": {
    "configuration": {
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
    }
  }
...
}
```

**Comment by Dynatrace-Adam-Gardner** [comment]
It would be great if `verbose` logging actually printed the payload being sent to Dynatrace. That'd help me diagnose this further.

**Comment by Dynatrace-Adam-Gardner** [comment]
So, a few things I've found here:

1. The string is being transformed within `monaco` to use backlashes rather than forward slashes: ` "userAgent": "Mozilla\5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\537.36 (KHTML, like Gecko) Chrome\86.0.4240.198 Safari\537.36"`
2. This string is then being interpreted as unescaped.

```
- ua_string: "Mozilla//5.0 (Windows NT 10.0; Win64; x64) AppleWebKit//537.36 (KHTML, like Gecko) Chrome//86.0.4240.198 Safari//537.36"
```
Would be processed by the tool (no failures). However, it is sent to Dynatrace  as:

```
"userAgent": "Mozilla\\5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\537.36 (KHTML, like Gecko) Chrome\\86.0.4240.198 Safari\\537.36"
```

This isn't a recognisable `UserAgent` string.

**Comment by Dynatrace-Adam-Gardner** [comment]
Related discussion: #21

**Comment by UnseenWizzard** [comment]
Hi @Dynatrace-Adam-Gardner. Sorry that we left you to figure this out on your own! 

Yes, as you correctly discovered this is an issue with how the tool currently attempts to handle paths OS independently. 
If put this bug at the top of our todo
