### ISSUE TITLE
Integration tests not cleaning up after themselves

### ISSUE THREAD

**Issue by tobigremmer-dt** [dynatrace-oss/dynatrace-monitoring-as-code#606]
**Describe the bug**
Dynatrace configurations are deployed as part of integration tests. Some of these configurations are not removed/reverted after tests are finished.

**How to reproduce**
- Create new Dynatrace environment (no pre-existing configs, entities, etc.)
- Clone repo
- Checkout main branch
- On your local machine set all required env vars (https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/CONTRIBUTING.md#integration-tests)
- Run:
```
make integration-tests
```

**Expected behavior**
All configs, entities, etc. are reset/removed upon an integration test run.

**Additional context**
Running cleanup scripts doesn't remove all configs either:
```
go test -tags=cleanup -v ./...
```

**Comment by UnseenWizzard** [comment]
closing as known issues for current v1.x tests; resolved for v2.x/next based test utils
