### ISSUE TITLE
Support new SLO API

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#66]
**Is your feature request related to a problem? Please describe.**
The new Dynatrace SLO API started as a preview feature in version 204. Customers, who are part of the preview should be able to leverage the SLO API using Monitoring as Code. Furthermore, when the feature goes GA, we already support it in monaco.

**Describe the solution you'd like**
Add support for the new SLO API and add a configuration used for the all-configs integration test.

**Comment by 163a** [comment]
Hu @didiladi is SLO described on here? https://www.dynatrace.com/support/help/whats-new/preview-and-early-adopter-releases/

**Comment by didiladi** [comment]
Hi @163a. The documentation on SLOs is not yet linked on dynatrace.com, but it will be soon.

If you are already interested in the SLO functionality, you can already take a look here: https://www.dynatrace.com/support/help/how-to-use-dynatrace/service-level-objectives/

It will be GA soon.
