### ISSUE TITLE
Monaco not updating entity selector data in management zone

### ISSUE THREAD

**Issue by tgyogesh** [dynatrace-oss/dynatrace-monitoring-as-code#697]
**Describe the bug**
When adding MZ entity selector field in json and run the monaco using 1.7 version, the entity selector values are not updated.
Sample json
{
 "description": null,
 "dimensionalRules": [],
 "entitySelectorBasedRules": [
    {
   "enabled": true,
   "entitySelector": "type(\"CUSTOM_DEVICE\"),tag(\"[AWS]Customer:{{.customerName}}\")"
  },
  {
   "enabled": true,
   "entitySelector": "type(\"CUSTOM_DEVICE_GROUP\"),toRelationships.isInstanceOf(type(\"CUSTOM_DEVICE\"),tag(\"[AWS]Customer:{{.customerName}}\"))"
  }
 ],

**Expected behavior**
The entity selector value has to be added in MZ

**Comment by UnseenWizzard** [comment]
Hi @tgyogesh. 
Could you please provide the log output of monaco in verbose mode (-v flag) when this happens? 

If I understand you correctly the config upload works but your change does not actually happen in Dynatrace?

**Comment by tgyogesh** [comment]
Hello @UnseenWizzard , 
Yes, you are correct. All changes are updated in MZ except the newly created entity selector rule.

**Comment by tgyogesh** [comment]
Attaching the verbose logs
[verboselogs.txt](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/files/9205786/verboselogs.txt)

**Comment by tgyogesh** [comment]
Hi @UnseenWizzard I see the entity selector rule section is blank when I check request.log file after running Monaco to update configuration.

    "description":  null,
    "dimensionalRules":  [

                         ],
    "entitySelectorBasedRules":  [

                                 ],

**Comment by tgyogesh** [comment]
HI @UnseenWizzard , Can I have any updates on this issue?

**Comment by UnseenWizzard** [comment]
Hi @tgyogesh, I was not able to reproduce this in a sample management-zone in which I've added the selectors you've had above... 

Deployment happens as it does in your log, but for me the MZ is updated with the selectors.
---

Could you please provide me with: 
1.  A minimal sample config that is failing for you (stripped of anything identifying configs)
2. The Dyntrace version you have this failing on

Thanks

**Comment by tgyogesh** [comment]
Hi @UnseenWizzard Please find below the template which we are using for MZ and we are using 1.7 version of Monaco.
{
 "description": null,
 "dimensionalRules": [],
 "entitySelectorBasedRules": [
    {
   "enabled": true,
   "entitySelector": "type(\"CUSTOM_DEVICE\"),tag(\"[AWS]Customer:{{.customerName}}\")"
  },
  {
   "enabled": true,
   "entitySelector": "type(\"CUSTOM_DEVICE_GROUP\"),toRelationships.isInstanceOf(type(\"CUSTOM_DEVICE\"),tag(\"[AWS]Customer:{{.customerName}}\"))"
  }
 ],
 "metadata": {
  "clusterVersion": "1.245.125.20220712-130121",
  "configurationVersions": [],
  "currentConfigurationVersions": [
   "1"
  ]
 },
 "name": "{{.name}}",
    "rules": [
        {
            "conditions": [
                {
                    "comparisonInfo": {
                        "negate": false,
                        "operator": "EQUALS",
                        "type": "TAG",
                        "value": {
                            "context": "AWS",
                            "key": "Customer",
                            "value": "{{.customerName}}"
                        }
                    },
                    "key": {
                        "attribute": "AWS_RELATIONAL_DATABASE_SERVICE_TAGS",
                        "type": "STATIC"
                    }
                }
            ],
            "enabled": true,
            "propagationTypes": [],
            "type": "AWS_RELATIONAL_DATABASE_SERVICE"
        },
        {
            "conditions": [
                {
                    "comparisonInfo": {
                        "negate": false,
                        "operator": "EQUALS",
                        "type": "SERVICE_TYPE",
                        "value": "DATABASE_SERVICE"
                    },
                    "key": {
                        "attribute": "SERVICE_TYPE",
                        "type": "STATIC"
                    }
                },
                {
                    "comparisonInfo": {
                        "negate": false,
                        "operator": "EQUALS",
                        "type": "TAG",
                        "value": {
                            "context": "AWS",
                            "key": "Customer",
                            "value": "{{.customerName}}"
                        }
                    },
                    "key": {
                        "attribute": "SERVICE_TAGS",
                        "type": "STATIC"
                    }
                }
            ],
            "enabled": true,
            "propagationTypes": [],
            "type": "SERVICE"
            },
            {
            "conditions": [
            {
            "comparisonInfo": {
            "negate": false,
            "operator": "EQUALS",
            "type": "TAG",
            "value": {
            "context": "AWS",
            "key": "Customer",
            "value": "{{.customerName}}"
            }
            },
            "key": {
            "attribute": "AWS_APPLICATION_LOAD_BALANCER_TAGS",
            "type": "STATIC"
            }
            }
            ],
            "enabled": true,
            "propagationTypes": [],
            "type": "AWS_APPLICATION_LOAD_BALANCER"
            }
            ]
            }

**Comment by Laubi** [comment]
Hi @tgyogesh, I am also investigating what is happening but could not reproduce the issue you're facing yet.
Your comment above that the entity-selector-rule section is blank also seems strange to me. We don't have any mechanism to replace sections of the JSON file in a manner that would result in an output like that. Could you please verify that you're editing the correct file? Or is the version you're working on stored as you expect it to be?
If I see correctly from your log file, you're working in an Azure environment. Might there be a synchronization issue?

As we haven't been able to reproduce this from the snippets so far, please provide a complete folder containing the JSON and yaml files for the management zone for which you're encountering this issue.
(Please strip any sensitive/identifying information from that config)

**Comment by tgyogesh** [comment]
My apologies. It works fine. There are 2 different MZ file which merges using a script and that is not handled to merge all the rules. Thanks for all your support.
