### ISSUE TITLE
Link to "supported APIs" in the documentation is dead

### ISSUE THREAD

**Issue by MatsLP** [dynatrace-oss/dynatrace-monitoring-as-code#736]
Hello,
the link in the docs that is supposed to show supported APIs does not work for me. Maybe this information moved?

Best Regards

![image](https://user-images.githubusercontent.com/24854917/189864288-6528648d-3cde-4a9a-98c8-a111fd7be5d1.png)

**Comment by UnseenWizzard** [comment]
Thanks for reporting this @MatsLP :+1: 
I've addressed this together with another documentation improvement in #737 - should be fixed soon
