### ISSUE TITLE
Add config line number to detected error

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#77]
Enhancement request to add the line number of the configuration when validator detects error in the configuration file(s).

`2020-12-01 14:36:10 ERROR Validation of sandbox failed with error projects/t24/request-naming-service/t24_webrequest_enquiry_operation.json is not a valid json! Error: invalid character '"' after object key:value pair`

**Comment by 163a** [comment]
Another example. It's like looking for a needle in a haystack when this occurs.

`2020-12-04 12:04:41 ERROR Validation of sandbox failed with error projects/t24/synthetic-monitor/t24_browser_monitors.json is not a valid json! Error: invalid character 'h' after object key:value pair`

**Comment by didiladi** [comment]
Just added a PR (#88) to add an additional log message if there are syntax errors in the json. Log messages would now look like that:

```
2020-12-07 19:52:12 ERROR File did not contain valid json:
 --> operation.json:7:4
   |    "no": "comma"
 7 |    "boolean": true
   |    ^^^
   - Cause: invalid character '"' after object key:value pair
```
