### ISSUE TITLE
Add version as a command line switch

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-monitoring-as-code#84]
**Is your feature request related to a problem? Please describe.**
I would like to know what version of the binary I am running

**Describe the solution you'd like**
add a switch such as `monoco version` or `monaco --version`

**Describe alternatives you've considered**
None

**Additional context**

**Comment by didiladi** [comment]
Nice enhancement! You are right, `monaco` should be able to return its own version.

If we go for `monaco version`, this can be handled alongside #45. I also like `monaco --version` or short `monaco --v`.

**Comment by mzball-dt** [comment]
I ran into this today - I had to re-download the binary to ensure I had v1.0.1

**Comment by didiladi** [comment]
@dynatrace-oss/mac-maintainers has anyone any preference whether to add `monaco version`, or `monaco --version`?

**Comment by patrickpichler** [comment]
I would go with `--version`. Almost all linux programs follow this "standard" (I'm not sure it this is formally a standard)

**Comment by UnseenWizzard** [comment]
+1 for `--version`. Even java finally fixed their `-version` ;) 

@robertjahn , @mzball-dt if you need to check the version, here's a (tedious) workaround until we've added this: 
monaco prints its version as the first log when running, but you'll need to point it at any file to get it there. 

e.g. with an empty `test.txt`
```> monaco -e test.txt 
2020-12-16 08:25:12 INFO  Dynatrace Monitoring as Code v1.0.0
^C
```

**Comment by robertjahn** [comment]
@patrickpichler  -- Is this change now part of a new release?   I am running 1.0.1 and I do not see the version yet?  I think that you all need to merge this change as part of new release like 1.0.2 before the readme gets updated into master.   Plus the current readme in master now has both reference to `-version` and `--version`.  Isn't it going to be just `--version` ?
![image](https://user-images.githubusercontent.com/24907089/102435745-2114bd00-3fe5-11eb-9f98-713c4042418b.png)

**Comment by patrickpichler** [comment]
Yes we need to release a new version of the tool.

Since the version in the master is already supporting the `--version` flag, 
it is fine to be merged already. You should always try to select your current
version tag to have the corresponding README to your version.

Since golang has a rather interesting philosophy regarding handling of
arguments, both version are possible. 

So you could write
```
monaco -version
```
or
```
monaco --version
```

I hope this answer all your questions.

A new release can be expected soon I guess.

**Comment by robertjahn** [comment]
I am a user of the "binary" so I was expecting that the readme's etc would align to these releases.   Now there are only 2 releases.  So this may be more feedback on release management of the code -- i.e. not merge to master unless it aligned to a the creation of a new release and corresponding binary.  
![image](https://user-images.githubusercontent.com/24907089/102499337-096f2000-4049-11eb-8942-6099d2e34324.png)
