### ISSUE TITLE
Azure subscription integration

### ISSUE THREAD

**Issue by JACONDE** [dynatrace-oss/dynatrace-monitoring-as-code#90]
I just tested the AWS credentials and it works really nice.
It will be great to have similar functionality for Azure.

**Comment by didiladi** [comment]
Hi, we already support the [Azure Credentials API](https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/azure-credentials-api/) in `monaco` (contributed by @kristofre). 

Just add your configs in a folder named `azure-credentials` and you are good to go.

I hope this is what you are looking for @JACONDE?

**Comment by JACONDE** [comment]
Thanks @didiladi, I will try this today and will come back to you and @kistofre if any issue. 
btw... is this in the documentation? I don't recall I saw this feature available

**Comment by didiladi** [comment]
You are absolutely right @JACONDE - we failed to add this in the [readme](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code#supported-configuration-types). Thanks for the hint! I just created #92 for extending the documentation.

**Comment by JACONDE** [comment]
Sounds great @didiladi, any other new feature not listed on the readme? ;-)

**Comment by didiladi** [comment]
Not that I'm aware of :smile:. But I'll double-check just to be sure.

**Comment by JACONDE** [comment]
Just tested and work nicely ! well done

**Comment by JACONDE** [comment]
I confirmed the azure integration is available and works as expected. It is pending add this feature to readme - case #92  open for this subject
