### ISSUE TITLE
aws credential

### ISSUE THREAD

**Issue by JACONDE** [dynatrace-oss/dynatrace-monitoring-as-code#91]
when creating a new aws account config, I'm getting  the following message:
"No connection to AWS for more than 20min. Please check your configuration."

![image](https://user-images.githubusercontent.com/11209831/101910162-d9de9480-3bbe-11eb-9f40-122a08dceebd.png)
and it is not collecting any data from aws.
Just need to open the aws credentials created, save it and start to work as expected.

**Comment by JACONDE** [comment]
I'm using the following .json file:
{
  "label": "{{ .name }}",
  "partitionType": "AWS_DEFAULT",
  "authenticationData": {
    "type": "ROLE",
    "roleBasedAuthentication": {
      "iamRole": "Dynatrace_monitoring_role",
      "accountId": "{{ .awsid }}"
    }
  },
  "taggedOnly": false,
  "tagsToMonitor": [
    {
      "name": "string",
      "value": "string"
    }
  ]
}

**Comment by didiladi** [comment]
HI @JACONDE. Thank you for the bug report. I'll forward this on Monday to the developers of the AWS credentials API.

**Comment by mmajcher** [comment]
Hi @JACONDE . I am able to reproduce the issue. 

It seems that the logic for error message is not correct. In my case, it seems that credentials (if they are valid) will turn to OK state after approx 2 minutes. Can you check if this is also the case for you?

In the meantime we are trying to fix this error message. It should say "Initializing".

**Comment by JACONDE** [comment]
let me double check that - I used the same credentials when created those integrations manually and they were ok.
I will come back to you on that

**Comment by JACONDE** [comment]
it seems to be working fine now - it is a bit weird when created, it shows as red in the screen, and then after collecting data in turns into black (normal status) - I'm closing the incident now. Thanks for your support
