### ISSUE TITLE
Support for the Azure Credentials API is not documented

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#92]
**Describe the bug**
The Azure credentials API is supported by `monaco`, but its not documented in the table in the [readme](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code#supported-configuration-types). This was dicovered in #90 by @JACONDE.

**Expected behavior**
Add the Azure credentials API (+ its token permissions) in the [README.md](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code#supported-configuration-types).

**Comment by kristofre** [comment]
@didiladi please assign this one to me

**Comment by 163a** [comment]
I added azure, kubernetes credentials to table while I was changing table for https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/187

with PR:
https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/pull/236

If happy, this issue may be closed too.

**Comment by CruzanCaramele** [comment]
closing this as was resolved by PR #236
